BOARD_COMPILER_FLAGS="-march=armv8.2-a+crc+crypto -mtune=cortex-a76"
BOARD_RUSTFLAGS="-C target-cpu=cortex-a76"
CHROMEOS_KERNEL_CONFIG="/mnt/host/source/src/overlays/project-rpi5/kconfig/kernel-6_12-r144-def-r1"

USE="${USE} -arc_disable_cros_video_decoder -disable_cros_video_decoder disable_explicit_dma_fences"
USE="${USE} v4l2_codec hevc_codec"

#TTY_CONSOLE="ttyAMA10"
