CHROMEOS_KERNEL_CONFIG="/mnt/host/source/src/overlays/project-rpi5/kconfig/kernel-6_6-r132-def-r1"

USE="${USE} -v4l2_codec -disable_explicit_dma_fences arc_disable_cros_video_decoder disable_cros_video_decoder"

#TTY_CONSOLE="ttyAMA10"
